#ifndef LIBKITDEMO2_GLOBAL_H
#define LIBKITDEMO2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBKITDEMO2_LIBRARY)
#  define LIBKITDEMO2_EXPORT Q_DECL_EXPORT
#else
#  define LIBKITDEMO2_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBKITDEMO2_GLOBAL_H
