# Generated by Django 3.0.6 on 2020-06-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsules',
            name='cup_color',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='capsules',
            name='cup_status_ng_ok',
            field=models.CharField(max_length=45),
        ),
    ]
