# Generated by Django 3.0.6 on 2020-06-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0002_auto_20200629_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsules',
            name='vendor',
            field=models.CharField(default='DJHS', max_length=45),
        ),
    ]
