# Generated by Django 3.0.6 on 2020-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('comment', models.CharField(max_length=40)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
